### ISSUE TITLE
Navigation Button

### ISSUE THREAD

**Issue by ghost** [mlyhoops/TorBots-Website#13]
Can the button show only for the narrow width? I think I was able to see the navigation lists before but now I have to click button to see the lists even on the big PC screen.

**Comment by mlyhoops** [comment]
fixed it show at 1000px. the only problem with this (I don't know how to fix it) is that when you try to make the screen smaller, the navbar crunches together and makes a thicker navbar that blocks certain items

**Comment by ghost** [comment]
I still see only the button as default in my big screen.
Do you want to refer my project(I got the sample coding originally)? https://fuji-pet-salon.herokuapp.com/
The change is fine when the screen is narrower. It should block the body content.

It has only four tabs so you can make
